usage = ("Commands are:\n"
        "-h, --help: Display this help message.\n"
        "-v, --version: Display the version.\n"
        "install: Install a program.\n"
        "remove: Remove a program.\n"
        "list: Show information about a program.\n"
        "\n Commands like install, remove, and list, but NOT like -h, --version, etc MUST be the FIRST ARGUMENT. The program name MUST be the SECOND ARGUMENT. Example:\n"
        "    thetechrobo install palc, or\n"
        "    thetechrobo list mathmod\n"
        "\nThanks for using TheTechRobo's package manager!"
)
